// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjzwuhulnkothyeidtik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indqend1aHVsbmtvdGh5ZWlkdGlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDE0NTEsImV4cCI6MjA2NTUxNzQ1MX0.WevC3GIcryvvLeHNCY8W_gOqDbIGtFDEUybsx91qprY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);